# Meta Data for SEO

## Homepage
title = "Nahwu101"
titleSeparator = "-"
titleAddition = "Pelajari Nahwu Lebih Mudah"
description = "Nahwu101 adalah website tentang belajar ilmu nahwu yang mudah difahami dengan menggunkan tampilan yang zaman now"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "farhanroy__"
twitterCreator = "farhanroy__"
facebookAuthor = "farhansekargadung"
facebookPublisher = "farhansekargadung"
ogLocale = "id_ID"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/farhanroy__"
schemaLinkedIn = "https://www.linkedin.com/in/farhanroy/"
schemaGitHub = "https://github.com/farhanroy"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/farhanroy/nahwu101/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/farhanroy/nahwu101"
editPage = false
